### ISSUE TITLE
User avatars should be resized

### ISSUE THREAD

**Issue by lwojcik** [jointwt/twtxt#270]
**Describe the bug**
I completely missed the point when it got changed but user avatars should get some preprocessing before saving. At the moment it's possible to upload [3000x4000 6 MB image](https://twtxt.net/user/prologic/avatar) that will be used as a 60x60 avatar which is very wasteful.

**To Reproduce**
Steps to reproduce the behaviour:
1. Upload a really big image as your avatar 
2. Use twtxt on a data-capped mobile plan or a very slow connection

**Expected behavior**
One of the following:
1. Web app shouldn't let me upload images that big and prompt me to resize them to more reasonable dimensions,
2. Web app should give preprocess the uploaded image so that properly scaled and optimized thumbnails are used

**Screenshots**
n/a

**Desktop (please complete the following information):**
all

**Smartphone (please complete the following information):**
all

**Additional context**
n/a

**Comment by prologic** [comment]
Do you have a good JavaScript library that will handle this for us without adding too much weight? 

The rescaling does automatically happen on the backend as well just in case￼￼￼

**Comment by lwojcik** [comment]
> The rescaling does automatically happen on the backend as well just in case￼￼￼

[It doesn't seem to work](https://i.imgur.com/cHn32nA.png).

The frontend has nothing to do with this and there's no need for a JavaScript library, it should be done on the backend. 3000x4000 image loaded as 60x60 avatar on a website is still 3000x4000 image, just visually rescaled by a web browser, i.e. excessive 6 megabytes spent on downloading something that shouldn't realistically weigh more than 20-50 kB.

**Comment by prologic** [comment]
Oooh that's a bug! Let me see...

**Comment by prologic** [comment]
Hmmm this is odd, I can't repro this locally 🤔

```#!console
[twtxt] 2020/11/15 07:21:52 (10.0.0.112:55620) "POST /settings HTTP/1.1" 200 2803 1.056124136s
[twtxt] 2020/11/15 07:21:55 (10.0.0.112:55620) "GET / HTTP/1.1" 200 4038 2.732084ms
[twtxt] 2020/11/15 07:21:55 (10.0.0.112:55620) "GET /user/admin/avatar HTTP/1.1" 200 110188 3.696399ms
INFO[0121] synced store
[twtxt] 2020/11/15 07:21:58 (10.0.0.112:55620) "GET /user/admin HTTP/1.1" 200 4653 3.192242ms
[twtxt] 2020/11/15 07:21:58 (10.0.0.112:55620) "GET /user/admin/avatar HTTP/1.1" 304 0 67.188µs
```

I end up with in `./data/avatars`:

```#!console
(⎈ |local:default)
prologic@Jamess-iMac
Sun Nov 15 07:23:17
~/Projects/jointwt/twtxt
 (master) 0
$ ls -lah data/avatars/
total 260K
drwxr-xr-x  5 prologic staff  160 Nov 15 07:21 .
drwxr-xr-x 12 prologic staff  384 Nov 14 12:00 ..
-rw-r--r--  1 prologic staff    0 Sep 14 07:53 .gitkeep
-rw-r--r--  1 prologic staff 151K Nov 15 07:21 admin.png
-rw-r--r--  1 prologic staff 108K Nov 15 07:21 admin.webp
```

Uploaded a ~3.8MB photo from my phone to a local dev pod.

Where are you seeing this? On Twtxt.net itself? It's running `master`.

**Comment by lwojcik** [comment]
Yes, twtxt.net.

**Comment by prologic** [comment]
And ImageMagick says it got downscaled to `270x360` (_which is correct as to what the backend is now doing_):

```#!console
(⎈ |local:default)
prologic@Jamess-iMac
Sun Nov 15 07:24:38
~/Projects/jointwt/twtxt
 (master) 0
$ magick identify data/avatars/admin.png
data/avatars/admin.png PNG 270x360 270x360+0+0 8-bit sRGB 153768B 0.000u 0:00.000
```

**Comment by prologic** [comment]
> Yes, twtxt.net.

I don't get how 😢 I guess I'll try there 😀

**Comment by prologic** [comment]
Whooah you're right! (_somehow_)

```#!console
/data/avatars # ls -lahS | head
total 17M
-rw-r--r--    1 501      dialout     9.2M Nov  8 11:39 prologic.png
-rw-r--r--    1 501      dialout     5.6M Nov  8 11:39 prologic.webp
-rw-r--r--    1 501      dialout   300.4K Nov  7 05:50 kt84.png
-rw-r--r--    1 501      dialout   208.5K Nov  7 05:50 kt84.webp
-rw-r--r--    1 501      dialout   176.5K Nov  8 01:13 dooven.png
-rw-r--r--    1 501      dialout   126.4K Nov  8 01:13 dooven.webp
-rw-r--r--    1 root     root      104.8K Nov  8 02:25 markwylde.png
-rw-r--r--    1 root     root       99.3K Nov  7 05:35 help.png
-rw-r--r--    1 501      dialout    90.2K Nov 11 21:04 birb.png
/data/avatars #
```

**Comment by prologic** [comment]
I don't get how I can't reproduce this locally :/

**Comment by lwojcik** [comment]
It looks fixed on my end now, your avatar has reasonable 270x360 pixels. :)

**Comment by prologic** [comment]
Wait what?! How?

**Comment by prologic** [comment]
Omg this is driving my crazy 😳

**Comment by lwojcik** [comment]
I don't know. Caching maybe? :)

**Comment by prologic** [comment]
WOW! This is fucking crazy!

All I did was update to`master` (Fixed in 3d3a820)

Nuked my own avatar on the filesystem and re-uploaded a new one:

It's now correct:

```#!console
/ # ls -lahS data/avatars/prologic.* | head
-rw-r--r--    1 root     root       86.2K Nov 14 22:00 data/avatars/prologic.png
-rw-r--r--    1 root     root       51.7K Nov 14 22:00 data/avatars/prologic.webp
```

Weird?

**Comment by prologic** [comment]
But I haven't actually changed the code, its still using the new imaging library https://github.com/disintegration/gift

I hope it doesn't have a weird bug

**Comment by prologic** [comment]
> I don't know. Caching maybe? :)

Caching of a `POST` request?! 🤣

**Comment by prologic** [comment]
@lwojcik Are you able to repro this anywhere now?

**Comment by lwojcik** [comment]
> Caching of a POST request?! rofl

There's still GET request while loading the page and this one can be cached I think.

I can't see it happening any more, seems to be working fine.

**Comment by prologic** [comment]
What I meant to say was I would upload a new test image and then check the file system! I could see the timestamp change but not the size it was really weird.

And it was only my avatar!
And it was only fixed once I nuked it on the file system and re-uploaded a brand new one!￼￼
￼￼

**Comment by prologic** [comment]
I _think_ this was a glitch left over from when I was mucking around with alternate image processing libraries and somehow landed a ~6MB avatar of myself on twtxt.net :/ Sorry about this! I cannot reproduce this locally and nor on twtxt.net and we believe this is resolved.
